spring:
  datasource:
    url: jdbc:mysql://localhost:3306/votacao?createDatabaseIfNotExist=true
    password: qwe123
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost